const DATA_URL='data.json';const STOP_TAGS=new Set(['www','http','https','.com','.cn','.io']);const LOCAL_KEY='nav_state_v2';
let raw=[];let state={dir:null,query:'',tagAnd:new Set(),tagOr:new Set(),tagNot:new Set(),selectedIds:new Set()};
const qs=(s,el=document)=>el.querySelector(s);
function normTag(t){if(!t)return'';const s=String(t).trim();if(STOP_TAGS.has(s.toLowerCase()))return'';return s;}
function getFavicon(u){try{const d=new URL(u).hostname;return `https://www.google.com/s2/favicons?sz=64&domain=${encodeURIComponent(d)}`}catch(e){return''}}
function save(){localStorage.setItem(LOCAL_KEY,JSON.stringify({dir:state.dir,query:state.query}))}
function load(){try{const s=JSON.parse(localStorage.getItem(LOCAL_KEY)||'{}');state.dir=state.dir||s.dir||null;state.query=s.query||''}catch(e){}}
function getParam(name){const p=new URLSearchParams(location.search);return p.get(name);}
function renderDirs(){const dirs=[...new Set(raw.map(x=>x.dir))].sort((a,b)=>String(a).localeCompare(String(b),'zh-Hans-CN'));const box=qs('#dirs');box.innerHTML=dirs.map(d=>`<div class="dir-item ${state.dir===d?'active':''}" data-dir="${d}">${d}</div>`).join('');box.onclick=e=>{const el=e.target.closest('.dir-item');if(!el)return;state.dir=el.dataset.dir;state.selectedIds.clear();state.tagAnd.clear();state.tagOr.clear();state.tagNot.clear();renderAll();history.replaceState({},'',`?dir=${encodeURIComponent(state.dir)}`)};if(!state.dir)state.dir=dirs[0]||null}
function currentItems(){if(!state.dir)return[];const q=state.query.trim().toLowerCase();let items=raw.filter(x=>x.dir===state.dir);if(q){items=items.filter(x=>x.title.toLowerCase().includes(q)||(x.desc||'').toLowerCase().includes(q)||x.url.toLowerCase().includes(q)||x.tags.some(t=>String(t).toLowerCase().includes(q)))}if(state.tagNot.size)items=items.filter(x=>!x.tags.some(t=>state.tagNot.has(t)));if(state.tagAnd.size)items=items.filter(x=>[...state.tagAnd].every(t=>x.tags.includes(t)));if(state.tagOr.size)items=items.filter(x=>x.tags.some(t=>state.tagOr.has(t)));return items}
function renderCards(){const items=currentItems();const box=qs('#content');box.innerHTML=items.map(x=>{const fav=getFavicon(x.url);const color=x.color?`style="background:${x.color}"`:'';return `<div class="card" ${color} data-id="${x.id}">
<input class="select-box" type="checkbox" ${state.selectedIds.has(x.id)?'checked':''} />
<img class="favicon" src="${fav}" alt="" />
<div><h4 class="card-title"><a href="${x.url}" target="_blank" rel="noopener">${x.title}</a></h4><p class="card-desc">${x.desc?x.desc:''}</p><div class="small muted">${x.url}</div></div></div>`}).join('');box.onclick=e=>{const card=e.target.closest('.card');if(!card)return;const id=card.dataset.id;if(e.target.classList.contains('select-box')){if(e.target.checked)state.selectedIds.add(id);else state.selectedIds.delete(id);updateToolbar();return}const a=card.querySelector('a');if(a&&!e.metaKey&&!e.ctrlKey)a.click()};updateToolbar()}
function renderTags(){const itemsInDir=raw.filter(x=>x.dir===state.dir);const counts=new Map();for(const it of itemsInDir){for(const t of it.tags){counts.set(t,(counts.get(t)||0)+1)}}const filtered=currentItems();const filteredCount=new Map();for(const it of filtered){for(const t of it.tags){filteredCount.set(t,(filteredCount.get(t)||0)+1)}}const tags=[...counts.keys()].sort((a,b)=>(filteredCount.get(b)||0)-(filteredCount.get(a)||0)||String(a).localeCompare(String(b),'zh-Hans-CN'));const box=qs('#taglist');box.innerHTML=tags.map(t=>{let cls='tag';if(state.tagAnd.has(t))cls+=' and';else if(state.tagOr.has(t))cls+=' or';else if(state.tagNot.has(t))cls+=' not';const c=filteredCount.get(t)||0;return `<div class="${cls}" data-tag="${t}">${t}<span class="count">(${c})</span></div>`}).join('');box.onclick=e=>{const el=e.target.closest('.tag');if(!el)return;const t=el.dataset.tag;const already=(state.tagAnd.size===1&&state.tagAnd.has(t)&&state.tagOr.size===0&&state.tagNot.size===0)||(state.tagOr.size===1&&state.tagOr.has(t)&&state.tagAnd.size===0&&state.tagNot.size===0)||(state.tagNot.size===1&&state.tagNot.has(t)&&state.tagAnd.size===0&&state.tagOr.size===0);state.tagAnd.clear();state.tagOr.clear();state.tagNot.clear();if(!already){if(e.altKey)state.tagNot.add(t);else if(e.shiftKey)state.tagOr.add(t);else state.tagAnd.add(t)}renderAll()};renderChips()}
function renderChips(){const wrap=qs('#activeChips');const chip=(op,t)=>`<span class="chip"><span class="op">${op}</span>${t}<button data-op="${op}" data-tag="${t}" title="移除">×</button></span>`;const arr=[...[...state.tagAnd].map(t=>chip('AND',t)), ...[...state.tagOr].map(t=>chip('OR',t)), ...[...state.tagNot].map(t=>chip('NOT',t))];wrap.innerHTML=arr.join('');wrap.onclick=e=>{if(e.target.tagName==='BUTTON'){const op=e.target.dataset.op,t=e.target.dataset.tag;if(op==='AND')state.tagAnd.delete(t);if(op==='OR')state.tagOr.delete(t);if(op==='NOT')state.tagNot.delete(t);renderAll()}}}
function updateToolbar(){const items=currentItems();const openSel=qs('#btnOpenSelected');openSel.disabled=state.selectedIds.size===0;openSel.textContent=`打开已选(${state.selectedIds.size})`;qs('#btnOpenAll').disabled=items.length===0}
function openMany(urls){let i=0;const t=setInterval(()=>{if(i>=urls.length){clearInterval(t);return}window.open(urls[i],'_blank','noopener');i++},120)}
qs('#btnOpenSelected').onclick=()=>{const ids=[...state.selectedIds];const items=currentItems().filter(x=>ids.includes(x.id));openMany(items.map(x=>x.url))};
qs('#btnOpenAll').onclick=()=>{const items=currentItems();openMany(items.map(x=>x.url))};
qs('#btnSelectAll').onclick=()=>{currentItems().forEach(x=>state.selectedIds.add(x.id));renderCards()};
qs('#btnInvert').onclick=()=>{const ids=new Set(currentItems().map(x=>x.id));const next=new Set();ids.forEach(id=>{if(!state.selectedIds.has(id))next.add(id)});state.selectedIds=next;renderCards()};
qs('#btnCopy').onclick=async()=>{const urls=currentItems().map(x=>x.url).join('\\n');try{await navigator.clipboard.writeText(urls);alert('已复制当前列表的链接到剪贴板')}catch(e){prompt('复制失败，请手动复制：',urls)}};
const search=qs('#search');search.value=state.query||'';search.oninput=e=>{state.query=e.target.value;renderAll()};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.focus();search.select()}if(e.key==='Escape'){state.query='';search.value='';state.tagAnd.clear();state.tagOr.clear();state.tagNot.clear();state.selectedIds.clear();renderAll()}});
function renderAll(){renderCards();renderTags();save()}
(async function init(){const res=await fetch(DATA_URL);const json=await res.json();raw=json.map((x,i)=>{const id=x.id||String(i);const title=x.title?.trim()||x.url;const dir=String(x.dir||'未分类').trim();const desc=x.desc||'';const url=x.url;const tags=(x.tags||[]).map(normTag).filter(Boolean);return{id,title,dir,desc,url,tags,pinned:!!x.pinned,weight:x.weight||0,hotkey:x.hotkey||'',color:x.color||''}});state.dir=getParam('dir')||state.dir;load();renderDirs();renderAll()})();